project:
  type: website
  output-dir: docs

website:
  title: "HaoxuanLi"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: projects.qmd
        text: Projects

      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
